language: python
python:
  - "3.6"
  # PyPy versions
  - "pypy3.5"
env:
  - FLASK=0.12.2
# command to install dependencies
install:
  - pip install flask==$FLASK
  - pip install -e .
# command to run tests
script: true